### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = int(input('Ведите число:'))
np.arange(N,0,-3)

Ведите число:15


array([15, 12,  9,  6,  3])

In [3]:
N = int(input('Ведите число:'))
np.arange(N,0,-5)

Ведите число:25


array([25, 20, 15, 10,  5])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
N = int(input('Ведите число:'))
##M = int(input('Ведите число'))
np.diag(np.arange(N,0,-3), k=0)

Ведите число:30


array([[30,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 27,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 24,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 21,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 18,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  3]])

In [5]:
## Считаем сумму элементов по диагонали
a = np.diag(np.arange(N,0,-3), k=0)

sum_diag = 0
for i, element in enumerate(a):
    sum_diag += element[i]
print(sum_diag)

165


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [6]:
from numpy import linalg

In [7]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4,]])
b = np.array([4, 12, -3])
from numpy import linalg
x = linalg.solve(a, b)
x

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
def cosine( users_stats, next_user_stats ):
    """
    Ищем косинус угла между векторами в каждой строчке матрицы user_stats и next_user_stats по их координатам
    """
    
    # длины векторов
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    
    
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )

In [14]:
muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
muls

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [15]:
### Самый подходящий пользователь, ID 7
best_user = np.argmax(muls)
best_user

7